<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Brand;
use App\Models\Category;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'San Miguel Pale Pilsen',
                'brand' => 'San Miguel Brewery',
                'category' => 'Lagers',
                'price' => 419.00,
                'description' => 'San Miguel Pale Pilsen is the iconic Filipino pale lager known for its crisp, well-balanced flavor and slightly bitter finish. It has been a cultural staple for over a century, enjoyed across all social settings. This beer pairs excellently with a wide variety of local dishes.',
                'stock' => 100,
                'image_url' => 'images/products/san-miguel-pale-pilsen/san-miguel-pale-pilsen.jpg',
                'alcohol_content' => 5.0,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => true,
                'rating' => 5,
            ],
            [
                'name' => 'Red Horse Beer',
                'brand' => 'San Miguel Brewery',
                'category' => 'Lagers',
                'price' => 369.00,
                'description' => 'Red Horse Beer is a bold, strong lager with a full-bodied malt character and higher alcohol content, favored for its intense flavor. It delivers a smooth yet powerful drinking experience, perfect for those who prefer a stronger beer. It is often consumed during festive and social occasions.',
                'stock' => 100,
                'image_url' => 'images/products/red-horse-beer/red-horse-beer.jpg',
                'alcohol_content' => 6.9,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => true,
                'rating' => 5,
            ],
            [
                'name' => 'San Mig Light',
                'brand' => 'San Miguel Brewery',
                'category' => 'Lagers',
                'price' => 369.00,
                'description' => 'A low-calorie, light lager offering a smooth and easy-drinking profile with subtle malt sweetness.',
                'stock' => 100,
                'image_url' => 'images/products/san-mig-light/san-mig-light.jpg',
                'alcohol_content' => 4.5,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 3,
            ],
            [
                'name' => 'Gold Eagle Beer',
                'brand' => 'San Miguel Brewery',
                'category' => 'Lagers',
                'price' => 375.00,
                'description' => 'A traditional lager with a slightly sweet malt character and a clean, crisp finish.',
                'stock' => 100,
                'image_url' => 'images/products/gold-eagle-beer/gold-eagle-beer.jpg',
                'alcohol_content' => 5.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Cerveza Negra',
                'brand' => 'San Miguel Brewery',
                'category' => 'Lagers',
                'price' => 474.00,
                'description' => 'A dark lager featuring rich caramel and roasted malt flavors with hints of coffee and chocolate.',
                'stock' => 100,
                'image_url' => 'images/products/cerveza-negra/cerveza-negra.jpg',
                'alcohol_content' => 5.3,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'San Miguel Super Dry',
                'brand' => 'San Miguel Brewery',
                'category' => 'Lagers',
                'price' => 462.50,
                'description' => 'A crisp, dry lager brewed for a clean and refreshing taste with a light body.',
                'stock' => 100,
                'image_url' => 'images/products/san-miguel-super-dry/san-miguel-super-dry.jpg',
                'alcohol_content' => 5.0,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 3,
            ],
            [
                'name' => 'San Miguel Premium All Malt Beer',
                'brand' => 'San Miguel Brewery',
                'category' => 'Lagers',
                'price' => 474.75,
                'description' => 'A premium all-malt lager brewed with 100% malt, offering a richer and more robust malt flavor.',
                'stock' => 100,
                'image_url' => 'images/products/san-miguel-premium/san-miguel-premium.jpg',
                'alcohol_content' => 5.5,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'San Mig Zero',
                'brand' => 'San Miguel Brewery',
                'category' => 'Lagers',
                'price' => 375.00,
                'description' => 'A non-alcoholic beer that retains the classic San Miguel Pale Pilsen taste without the alcohol.',
                'stock' => 100,
                'image_url' => 'images/products/san-mig-zero/san-mig-zero.jpg',
                'alcohol_content' => 0.0,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 3,
            ],
            [
                'name' => 'Red Horse Super',
                'brand' => 'San Miguel Brewery',
                'category' => 'Lagers',
                'price' => 425.00,
                'description' => 'An extra-strong variant of the classic Red Horse, with higher alcohol content and a more intense malt profile.',
                'stock' => 100,
                'image_url' => 'images/products/red-horse-super/red-horse-super.jpg',
                'alcohol_content' => 7.5,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'San Miguel Strong Ice',
                'brand' => 'San Miguel Brewery',
                'category' => 'Stouts',
                'price' => 375.00,
                'description' => 'San Miguel Strong Ice is a malt liquor with stout-like characteristics, combining a strong alcohol kick with a creamy, smooth mouthfeel. It blends the richness of stout with the refreshing qualities of malt liquor. This beer is popular among drinkers seeking variety and strength.',
                'stock' => 100,
                'image_url' => 'images/products/san-miguel-strong-ice/san-miguel-strong-ice.jpg',
                'alcohol_content' => 7.5,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'San Miguel Apple Ale',
                'brand' => 'San Miguel Brewery',
                'category' => 'Ales',
                'price' => 354.00,
                'description' => 'A fruit ale that infuses crisp apple flavors into a light ale base.',
                'stock' => 100,
                'image_url' => 'images/products/san-miguel-apple-ale/san-miguel-apple-ale.jpg',
                'alcohol_content' => 4.2,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 3,
            ],
            [
                'name' => 'San Miguel Flavored Beer Mango',
                'brand' => 'San Miguel Brewery',
                'category' => 'Wheat Beers',
                'price' => 419.00,
                'description' => 'A wheat ale with tropical mango notes, creating a refreshing and aromatic drink.',
                'stock' => 100,
                'image_url' => 'images/products/san-miguel-mango/san-miguel-mango.jpg',
                'alcohol_content' => 4.0,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'San Miguel Flavored Beer Lemon',
                'brand' => 'San Miguel Brewery',
                'category' => 'Wheat Beers',
                'price' => 419.00,
                'description' => 'A wheat ale with zesty lemon notes, creating a refreshing and aromatic drink.',
                'stock' => 100,
                'image_url' => 'images/products/san-miguel-lemon/san-miguel-lemon.jpg',
                'alcohol_content' => 4.0,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Beer na Beer',
                'brand' => 'Asia Brewery',
                'category' => 'Lagers',
                'price' => 375.00,
                'description' => 'Beer na Beer is a classic pale pilsen with a clean, crisp taste and mild hop bitterness. It is an easy-to-drink lager that has been a long-time favorite in the Philippine market. This beer pairs well with many Filipino dishes.',
                'stock' => 100,
                'image_url' => 'images/products/beer-na-beer/beer-na-beer.jpg',
                'alcohol_content' => 5.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => true,
                'rating' => 4,
            ],
            [
                'name' => 'Colt 45',
                'brand' => 'Asia Brewery',
                'category' => 'Lagers',
                'price' => 380.00,
                'description' => 'Colt 45 is a malt liquor with higher alcohol content and a smooth, slightly sweet malt flavor. Known for its strong kick, it appeals to drinkers seeking a more potent beer. The full-bodied taste balances strength with drinkability.',
                'stock' => 100,
                'image_url' => 'images/products/colt-45/colt-45.jpg',
                'alcohol_content' => 7.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Lone Star',
                'brand' => 'Asia Brewery',
                'category' => 'Lagers',
                'price' => 345.00,
                'description' => 'A refreshing lager with a light malt character and subtle hop bitterness.',
                'stock' => 100,
                'image_url' => 'images/products/lone-star/lone-star.jpg',
                'alcohol_content' => 5.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 3,
            ],
            [
                'name' => 'Lone Star Light',
                'brand' => 'Asia Brewery',
                'category' => 'Lagers',
                'price' => 345.00,
                'description' => 'A lighter body and fewer calories than the original, with a clean, crisp taste.',
                'stock' => 100,
                'image_url' => 'images/products/lone-star-light/lone-star-light.jpg',
                'alcohol_content' => 4.2,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 3,
            ],
            [
                'name' => 'Lone Star ULTRA',
                'brand' => 'Asia Brewery',
                'category' => 'Lagers',
                'price' => 375.00,
                'description' => 'A low-carb lager designed for health-conscious consumers.',
                'stock' => 100,
                'image_url' => 'images/products/lone-star-ultra/lone-star-ultra.jpg',
                'alcohol_content' => 4.0,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 3,
            ],
            [
                'name' => 'Colt Ice',
                'brand' => 'Asia Brewery',
                'category' => 'Lagers',
                'price' => 375.00,
                'description' => 'A chilled malt liquor variant with smooth malt sweetness and higher alcohol content.',
                'stock' => 100,
                'image_url' => 'images/products/colt-ice/colt-ice.jpg',
                'alcohol_content' => 7.2,
                'container_type' => 'Can',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Engkanto Pale Ale',
                'brand' => 'Engkanto Brewery',
                'category' => 'Ales',
                'price' => 180.00,
                'description' => 'Engkanto Pale Ale is a balanced ale with floral hop aromas and a crisp, refreshing finish. It features moderate bitterness complemented by a malt backbone. This beer is a favorite among local craft beer enthusiasts.',
                'stock' => 100,
                'image_url' => 'images/products/engkanto-pale-ale/engkanto-pale-ale.jpg',
                'alcohol_content' => 5.5,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => true,
                'rating' => 5,
            ],
            [
                'name' => 'Engkanto IPA',
                'brand' => 'Engkanto Brewery',
                'category' => 'Ales',
                'price' => 175.00,
                'description' => 'Delivers intense hop flavors with citrus and pine notes balanced by malt sweetness.',
                'stock' => 100,
                'image_url' => 'images/products/engkanto-ipa/engkanto-ipa.jpg',
                'alcohol_content' => 6.2,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Engkanto Double IPA',
                'brand' => 'Engkanto Brewery',
                'category' => 'Ales',
                'price' => 200.00,
                'description' => 'A stronger hop bitterness and higher alcohol content than the standard IPA.',
                'stock' => 100,
                'image_url' => 'images/products/engkanto-double-ipa/engkanto-double-ipa.jpg',
                'alcohol_content' => 8.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Engkanto Mango Ale',
                'brand' => 'Engkanto Brewery',
                'category' => 'Ales',
                'price' => 175.00,
                'description' => 'Blends ripe mango sweetness with a smooth ale base.',
                'stock' => 100,
                'image_url' => 'images/products/engkanto-mango-ale/engkanto-mango-ale.jpg',
                'alcohol_content' => 5.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Engkanto Wheat Beer',
                'brand' => 'Engkanto Brewery',
                'category' => 'Wheat Beers',
                'price' => 175.00,
                'description' => 'A light, cloudy wheat ale with banana and clove notes from yeast.',
                'stock' => 100,
                'image_url' => 'images/products/engkanto-wheat-beer/engkanto-wheat-beer.jpg',
                'alcohol_content' => 5.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Engkanto Stout',
                'brand' => 'Engkanto Brewery',
                'category' => 'Stouts',
                'price' => 200.00,
                'description' => 'Engkanto Stout is a rich, dark beer with roasted malt flavors of coffee and chocolate. It has a creamy mouthfeel and smooth, slightly bitter finish. Ideal for fans of bold dark beers.',
                'stock' => 100,
                'image_url' => 'images/products/engkanto-stout/engkanto-stout.jpg',
                'alcohol_content' => 6.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Island Hopper IPA',
                'brand' => 'The Cebruery',
                'category' => 'Ales',
                'price' => 220.00,
                'description' => 'Island Hopper IPA bursts with tropical fruit and pine aromas, balanced by a solid malt backbone. It is aromatic and refreshing, perfect for IPA lovers seeking a vibrant local brew. The crisp finish makes it ideal for warm weather.',
                'stock' => 100,
                'image_url' => 'images/products/island-hopper-ipa/island-hopper-ipa.jpg',
                'alcohol_content' => 6.5,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => true,
                'rating' => 5,
            ],
            [
                'name' => 'Cebuano Pale Ale',
                'brand' => 'The Cebruery',
                'category' => 'Ales',
                'price' => 175.00,
                'description' => 'Offers a smooth malt profile with citrusy hop character and a balanced bitterness.',
                'stock' => 100,
                'image_url' => 'images/products/cebuano-pale-ale/cebuano-pale-ale.jpg',
                'alcohol_content' => 5.2,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'People Power Pale Ale',
                'brand' => 'The Cebruery',
                'category' => 'Ales',
                'price' => 200.00,
                'description' => 'Medium-bodied with bright hop aromas and a crisp, balanced taste.',
                'stock' => 100,
                'image_url' => 'images/products/people-power-pale-ale/people-power-pale-ale.jpg',
                'alcohol_content' => 5.5,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Fat Bottomed Girl',
                'brand' => 'The Cebruery',
                'category' => 'Ales',
                'price' => 245.00,
                'description' => 'A rich Scotch Ale with caramel and toffee notes.',
                'stock' => 100,
                'image_url' => 'images/products/fat-bottomed-girl/fat-bottomed-girl.jpg',
                'alcohol_content' => 7.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Pedro Pale Ale',
                'brand' => 'Pedro Brewcrafters',
                'category' => 'Ales',
                'price' => 180.00,
                'description' => 'Pedro Pale Ale is a balanced ale with floral hop aromas and a smooth malt backbone. Crisp and refreshing, it is ideal for everyday drinking. The beer showcases excellent local brewing craftsmanship.',
                'stock' => 100,
                'image_url' => 'images/products/pedro-pale-ale/pedro-pale-ale.jpg',
                'alcohol_content' => 5.2,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => true,
                'rating' => 5,
            ],
            [
                'name' => 'Pedro Session IPA',
                'brand' => 'Pedro Brewcrafters',
                'category' => 'Ales',
                'price' => 175.00,
                'description' => 'Bold hop flavors with lower alcohol content for easy drinking.',
                'stock' => 100,
                'image_url' => 'images/products/pedro-session-ipa/pedro-session-ipa.jpg',
                'alcohol_content' => 4.5,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Pedro Coffee Ale',
                'brand' => 'Pedro Brewcrafters',
                'category' => 'Ales',
                'price' => 200.00,
                'description' => 'Combines rich coffee flavors with a smooth ale base.',
                'stock' => 100,
                'image_url' => 'images/products/pedro-coffee-ale/pedro-coffee-ale.jpg',
                'alcohol_content' => 5.5,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Crazy Carabao Pale Ale',
                'brand' => 'Crazy Carabao',
                'category' => 'Ales',
                'price' => 170.00,
                'description' => 'Crazy Carabao Pale Ale is a vibrant ale with citrus and floral hop notes balanced by malt sweetness. Refreshing and easy to drink, it showcases local craft talent. Perfect for casual social gatherings.',
                'stock' => 100,
                'image_url' => 'images/products/crazy-carabao-pale-ale/crazy-carabao-pale-ale.jpg',
                'alcohol_content' => 5.5,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Crazy Carabao Stout',
                'brand' => 'Crazy Carabao',
                'category' => 'Stouts',
                'price' => 200.00,
                'description' => 'Offers roasted malt flavors with hints of chocolate and coffee.',
                'stock' => 100,
                'image_url' => 'images/products/crazy-carabao-stout/crazy-carabao-stout.jpg',
                'alcohol_content' => 6.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Crazy Carabao Pilsner',
                'brand' => 'Crazy Carabao',
                'category' => 'Lagers',
                'price' => 175.00,
                'description' => 'A crisp, clean lager with light malt sweetness and subtle hop bitterness.',
                'stock' => 100,
                'image_url' => 'images/products/crazy-carabao-pilsner/crazy-carabao-pilsner.jpg',
                'alcohol_content' => 5.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 3,
            ],
            [
                'name' => 'Nipa Pale Ale',
                'brand' => 'Nipa Brew',
                'category' => 'Ales',
                'price' => 170.00,
                'description' => 'Nipa Pale Ale features bright hop aromas with citrus and floral notes. Balanced with a malt backbone and clean finish, it is a fresh take on the classic pale ale style. The beer showcases local craft innovation.',
                'stock' => 100,
                'image_url' => 'images/products/nipa-pale-ale/nipa-pale-ale.jpg',
                'alcohol_content' => 5.4,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Nipa Hoppy Lager',
                'brand' => 'Nipa Brew',
                'category' => 'Lagers',
                'price' => 175.00,
                'description' => 'Combines the crispness of a lager with aromatic hop character of an ale.',
                'stock' => 100,
                'image_url' => 'images/products/nipa-hoppy-lager/nipa-hoppy-lager.jpg',
                'alcohol_content' => 5.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => 'Alamat Ube Stout',
                'brand' => 'Alamat Brewery',
                'category' => 'Stouts',
                'price' => 240.00,
                'description' => 'Alamat Ube Stout is a unique stout brewed with ube (purple yam), lending subtle sweetness and earthy flavor. Rich roasted malt notes and creamy mouthfeel make it a standout. This beer artfully blends Filipino flavors with stout tradition.',
                'stock' => 100,
                'image_url' => 'images/products/alamat-ube-stout/alamat-ube-stout.jpg',
                'alcohol_content' => 6.5,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => true,
                'rating' => 5,
            ],
            [
                'name' => 'Adlai Rice Lager',
                'brand' => 'Alamat Brewery',
                'category' => 'Lagers',
                'price' => 190.00,
                'description' => 'Adlai Rice Lager is brewed using adlai, a local grain, resulting in a light, crisp lager with a slightly nutty flavor. Refreshing and smooth, it showcases indigenous ingredients. The beer is perfect for those seeking distinct Filipino craft brews.',
                'stock' => 100,
                'image_url' => 'images/products/adlai-rice-lager/adlai-rice-lager.jpg',
                'alcohol_content' => 5.0,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
            [
                'name' => "Fat Pauly's IPA",
                'brand' => 'The Cebruery',
                'category' => 'Ales',
                'price' => 200.00,
                'description' => "Fat Pauly's IPA is a hop-forward ale with citrus and pine aromas balanced by malt sweetness. Bold and aromatic, it appeals to craft beer lovers. The beer finishes crisp and refreshing.",
                'stock' => 100,
                'image_url' => 'images/products/fat-paulys-ipa/fat-paulys-ipa.jpg',
                'alcohol_content' => 6.5,
                'container_type' => 'Bottle',
                'volume' => '330ml',
                'is_featured' => false,
                'rating' => 4,
            ],
        ];

        foreach ($products as $product) {
            $brand = Brand::where('name', $product['brand'])->first();
            $category = Category::where('name', $product['category'])->first();
            
            if ($brand && $category) {
                $slug = Str::slug($product['name']);
                Product::create([
                    'name' => $product['name'],
                    'slug' => $slug,
                    'description' => $product['description'],
                    'price' => $product['price'],
                    'stock' => $product['stock'],
                    'image_url' => str_replace('.jpg', '', $product['image_url']) . '/' . $slug . '.jpg',
                    'alcohol_content' => $product['alcohol_content'],
                    'container_type' => $product['container_type'],
                    'volume' => $product['volume'],
                    'is_featured' => $product['is_featured'],
                    'rating' => $product['rating'],
                    'brand_id' => $brand->id,
                    'category_id' => $category->id,
                    'quantity' => rand(50, 200),
                    'quantity_sold' => rand(10, 100)
                ]);
            }
        }
    }
} 